#!/usr/bin/env python
# coding: utf-8


# -*- coding: utf-8 -*-
# Created on Wed Aug 05 11:06:45 2020
# @author: Seongmin Bak, TES
#
#

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time
import urllib
#import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebKit import *
from PyQt5.QtWebKitWidgets import *
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TES main")
        MainWindow.resize(1200, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 0, 1181, 871))
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setToolTipDuration(-1)

        # Setup tab
        self.tab_setup.setObjectName("tab_setup")
        self.lineEdit_proposal = QtWidgets.QLineEdit(self.tab_setup)
        self.lineEdit_proposal.setGeometry(QtCore.QRect(90, 11, 116, 20))
        self.lineEdit_proposal.setObjectName("lineEdit_proposal")
        self.lineEdit_SAF = QtWidgets.QLineEdit(self.tab_setup)
        self.lineEdit_SAF.setGeometry(QtCore.QRect(90, 41, 116, 20))
        self.lineEdit_SAF.setObjectName("lineEdit_SAF")
        self.lineEdit_username = QtWidgets.QLineEdit(self.tab_setup)
        self.lineEdit_username.setGeometry(QtCore.QRect(90, 71, 116, 19))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_Proposal = QtWidgets.QLabel(self.tab_setup)
        self.label_Proposal.setGeometry(QtCore.QRect(11, 11, 65, 16))
        self.label_Proposal.setObjectName("label_Proposal")
        self.label_SAF = QtWidgets.QLabel(self.tab_setup)
        self.label_SAF.setGeometry(QtCore.QRect(11, 41, 36, 16))
        self.label_SAF.setObjectName("label_SAF")
        self.label_username = QtWidgets.QLabel(self.tab_setup)
        self.label_username.setGeometry(QtCore.QRect(11, 71, 81, 16))
        self.label_username.setObjectName("label_username")
        self.comboBox_edgeselect = QtWidgets.QComboBox(self.tab_setup)
        self.comboBox_edgeselect.setGeometry(QtCore.QRect(363, 10, 104, 26))
        self.comboBox_edgeselect.setMouseTracking(False)
        self.comboBox_edgeselect.setAcceptDrops(True)
        self.comboBox_edgeselect.setObjectName("comboBox_edgeselect")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")
        self.comboBox_edgeselect.addItem("")

        self.label_edge = QtWidgets.QLabel(self.tab_setup)
        self.label_edge.setGeometry(QtCore.QRect(290, 10, 60, 16))
        self.label_edge.setObjectName("label_edge")
        self.label_edgeE = QtWidgets.QLabel(self.tab_setup)
        self.label_edgeE.setGeometry(QtCore.QRect(250, 40, 81, 16))
        self.label_edgeE.setObjectName("label_edgeE")

        # button for moveE
        self.Btn_moveE = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_moveE.setGeometry(QtCore.QRect(470, 66, 113, 32))
        self.Btn_moveE.setObjectName("Btn_moveE")
        # self.Btn_moveE.clicked.connect(self.""#mono energy = Cpt(EpicsMotor, "x08bm:mon"))

        # Webcam1
        self.tabWidget_webcam = QtWidgets.QTabWidget(self.tab_setup)
        self.tabWidget_webcam.setGeometry(QtCore.QRect(20, 150, 461, 401))
        self.tabWidget_webcam.setObjectName("tabWidget_webcam")
        self.tab_cam01 = QtWidgets.QWidget()
        self.tab_cam01.setObjectName("tab_cam01")
        self.tabWidget_webcam.addTab(self.tab_cam01, "cam1")
           
        

        # load webcam1
        #tab_cam01 = cv2.VideoCapture('rtsp://admin:admin@10.8.129.33')
        #while (True):
            #ret, frame = tab_cam01.read()
        #cv2.imshow('cam1', frame)

        #cap.release()
        #cv2.destroyAllWindows()

        # Webcam2
        self.tab_cam02 = QtWidgets.QWidget()
        self.tab_cam02.setObjectName("tab_cam02")
        self.tabWidget_webcam.addTab(self.tab_cam02, "cam2")

        #load webcam 2
        #tab_cam02 = cv2.VideoCapture('rtsp://admin:admin@10.8.129.33')
        #while (True):
            #ret, frame = tab_cam01.read()
        #cv2.imshow('cam2', frame)
        
        #cap.release()
        #cv2.destroyAllWindows()

       ## move stage
        self.Btn_up = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_up.setGeometry(QtCore.QRect(270, 600, 71, 41))
        self.Btn_up.setObjectName("Btn_up")
        self.Btn_up.clicked.connect(self.stage_up)

        self.Btn_right = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_right.setGeometry(QtCore.QRect(270, 560, 71, 41))
        self.Btn_right.setObjectName("Btn_right")
        self.Btn_right.clicked.connect(self.stage_right)
        
        self.Btn_left = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_left.setGeometry(QtCore.QRect(80, 560, 71, 41))
        self.Btn_left.setObjectName("Btn_left")
        self.Btn_left.clicked.connect(self.stage_left)

        self.Btn_down = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_down.setGeometry(QtCore.QRect(80, 600, 71, 41))
        self.Btn_down.setObjectName("Btn_down")
        self.Btn_down.clicked.connect(self.stage_down)

        # adjustment of z (focus)
        self.Btn_zoomout = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_zoomout.setGeometry(QtCore.QRect(270, 640, 71, 41))
        self.Btn_zoomout.setObjectName("Btn_zoomout")
        self.Btn_zoomout.clicked.connect(self.zoomout)

        self.Btn_zoomin = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_zoomin.setGeometry(QtCore.QRect(80, 640, 71, 41))
        self.Btn_zoomin.setObjectName("Btn_zoomin")
        self.Btn_zoomin.clicked.connect(self.zoomin)

        def stage_up(self):
            v_step = self.spinBox_ver_step.value()
            self.RE(bps.mvr(self.sample_stage.y, v_step))
            self.show_image()
         
        def stage_down(self):
            v_step = self.spinBox_ver_step.value()
            self.RE(bps.mvr(self.sample_stage.y, -v_step))
            self.show_image()

        def stage_right(self):
            h_step = self.spinBox_hor_step.value()
            self.RE(bps.mvr(self.sample_stage.x, -h_step))
            self.show_image()

        def stage_left(self):
            h_step = self.spinBox_hor_step.value()
            self.RE(bps.mvr(self.sample_stage.x, h_step))
            self.show_image()
        
        def zoomout(self):
            z_step = self.spinBox_z_step.value()
            self.RE(bps.mvr(self.sample_stage.z, z_step))
            self.show_image()
            
        def zoomin(self):
            z_step = self.spinBox_z_step.value()
            self.RE(bps.mvr(self.sample_stage.z, z_step))
            self.show_image() 
        
        
        
        
        
        
        
        self.label_zpos = QtWidgets.QLabel(self.tab_setup)
        self.label_zpos.setGeometry(QtCore.QRect(200, 650, 60, 16))
        self.label_zpos.setObjectName("label_zpos")

        self.lineEdit_monoE = QtWidgets.QLineEdit(self.tab_setup)
        self.lineEdit_monoE.setGeometry(QtCore.QRect(353, 70, 113, 21))
        self.lineEdit_monoE.setObjectName("lineEdit_monoE")

        self.label_monoE = QtWidgets.QLabel(self.tab_setup)
        self.label_monoE.setGeometry(QtCore.QRect(250, 70, 81, 16))
        self.label_monoE.setObjectName("label_monoE")

        self.label_currentE = QtWidgets.QLabel(self.tab_setup)
        self.label_currentE.setGeometry(QtCore.QRect(250, 100, 91, 16))
        self.label_currentE.setObjectName("label_currentE")

        self.scrollArea_Xpress3 = QtWidgets.QScrollArea(self.tab_setup)
        self.scrollArea_Xpress3.setGeometry(QtCore.QRect(500, 160, 351, 391))
        self.scrollArea_Xpress3.setWidgetResizable(True)
        self.scrollArea_Xpress3.setObjectName("scrollArea_Xpress3")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_Xpress3.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_DetCh = QtWidgets.QScrollArea(self.tab_setup)
        self.scrollArea_DetCh.setGeometry(QtCore.QRect(870, 160, 241, 391))
        self.scrollArea_DetCh.setWidgetResizable(True)
        self.scrollArea_DetCh.setObjectName("scrollArea_DetCh")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 389))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_DetCh.setWidget(self.scrollAreaWidgetContents_2)

        # save the motor position to the table
        self.Btn_save_current_position = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_save_current_position.setGeometry(QtCore.QRect(70, 780, 161, 32))
        self.Btn_save_current_position.setObjectName("Btn_save_current_position")
        # self.Btn_save_current_position.clicked.connect(self.""#read motor position and past to "tableWidget_samplepos"))

        # opne/close shutter
        self.Btn_shutter = QtWidgets.QPushButton(self.tab_setup)
        self.Btn_shutter.setGeometry(QtCore.QRect(980, 10, 131, 121))
        self.Btn_shutter.setObjectName("Btn_shutter")

        # Table for sample position info
        self.tableWidget_samplepos = QtWidgets.QTableWidget(self.tab_setup)
        self.tableWidget_samplepos.setGeometry(QtCore.QRect(500, 560, 611, 251))
        self.tableWidget_samplepos.setObjectName("tableWidget_samplepos")
        self.tableWidget_samplepos.setColumnCount(4)
        self.tableWidget_samplepos.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_samplepos.setHorizontalHeaderItem(3, item)
      
    
####################################################################  
       # table input for sample position 
        #def dataframe_generation_from_tableWidget_samplepos(self,tableWidget_samplepos):
    #number_of_rows = table.rowCount()
    #number_of_columns = table.columnCount()

    #tmp_df = pd.DataFrame({ 'Date' : [] , str(self.final_lvl_of_analysis) :[],  'Value': []}) 

    #for i in range(0,number_of_rows):
        #for j in range(0,number_of_columns):
            #tmp_item = table.item(i,j)
            #tmp_df2 = pd.DataFrame( { 'Date' : [pd.to_datetime(table.horizontalHeaderItem(j).data())] , str(self.final_lvl_of_analysis) :[ str(table.verticalHeaderItem(i).data())], 'Value': [float(tmp_item.data(0))]})
            #print tmp_df2
            #tmp_df.update(tmp_df2, join = 'left', overwrite = False)

    #return tmp_df
##########################################################################
        

        # tab for monitoring the Xpress3
        self.label_Xpress3 = QtWidgets.QLabel(self.tab_setup)
        self.label_Xpress3.setGeometry(QtCore.QRect(510, 140, 60, 16))
        self.label_Xpress3.setObjectName("label_Xpress3")
        self.label_ypos = QtWidgets.QLabel(self.tab_setup)
        self.label_ypos.setGeometry(QtCore.QRect(200, 610, 60, 16))
        self.label_ypos.setObjectName("label_ypos")
        self.label_xpos = QtWidgets.QLabel(self.tab_setup)
        self.label_xpos.setGeometry(QtCore.QRect(200, 570, 60, 16))
        self.label_xpos.setObjectName("label_xpos")
        self.label_11 = QtWidgets.QLabel(self.tab_setup)
        self.label_11.setGeometry(QtCore.QRect(80, 710, 71, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.tab_setup)
        self.label_12.setGeometry(QtCore.QRect(80, 730, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_setup)
        self.label_13.setGeometry(QtCore.QRect(80, 750, 71, 16))
        self.label_13.setObjectName("label_13")
        self.label_CurrentE_display = QtWidgets.QLabel(self.tab_setup)
        self.label_CurrentE_display.setGeometry(QtCore.QRect(370, 100, 121, 16))
        self.label_CurrentE_display.setObjectName("label_CurrentE_display")
        self.label_edgeE_display = QtWidgets.QLabel(self.tab_setup)
        self.label_edgeE_display.setGeometry(QtCore.QRect(370, 40, 121, 16))
        self.label_edgeE_display.setObjectName("label_edgeE_display")

        # XASfly tab
        self.tabWidget_main.addTab(self.tab_setup, "")
        self.tab_XASfly = QtWidgets.QWidget()
        self.tab_XASfly.setObjectName("tab_XASfly")
        self.label_XASfly_param = QtWidgets.QLabel(self.tab_XASfly)
        self.label_XASfly_param.setGeometry(QtCore.QRect(70, 50, 171, 16))
        self.label_XASfly_param.setObjectName("label_XASfly_param")
        self.tableWidget_XASfly = QtWidgets.QTableWidget(self.tab_XASfly)
        self.tableWidget_XASfly.setGeometry(QtCore.QRect(60, 70, 861, 161))
        self.tableWidget_XASfly.setAlternatingRowColors(True)
        self.tableWidget_XASfly.setObjectName("tableWidget_XASfly")
        self.tableWidget_XASfly.setColumnCount(8)
        self.tableWidget_XASfly.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASfly.setHorizontalHeaderItem(7, item)
        self.Efly_plot = PlotWidget(self.tab_XASfly)
        self.Efly_plot.setGeometry(QtCore.QRect(60, 300, 1011, 511))
        self.Efly_plot.setObjectName("Efly_plot")
        self.label_Efly_scan = QtWidgets.QLabel(self.tab_XASfly)
        self.label_Efly_scan.setGeometry(QtCore.QRect(80, 265, 81, 16))
        self.label_Efly_scan.setObjectName("label_Efly_scan")
        self.comboBox_Efly_single = QtWidgets.QComboBox(self.tab_XASfly)
        self.comboBox_Efly_single.setGeometry(QtCore.QRect(180, 263, 104, 26))
        self.comboBox_Efly_single.setMouseTracking(False)
        self.comboBox_Efly_single.setAcceptDrops(True)
        self.comboBox_Efly_single.setObjectName("comboBox_Efly_single")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.comboBox_Efly_single.addItem("")
        self.label_Efly_single_sample = QtWidgets.QLabel(self.tab_XASfly)
        self.label_Efly_single_sample.setGeometry(QtCore.QRect(180, 243, 81, 16))
        self.label_Efly_single_sample.setObjectName("label_Efly_single_sample")
        self.Btn_StartScan_single_Efly = QtWidgets.QPushButton(self.tab_XASfly)
        self.Btn_StartScan_single_Efly.setGeometry(QtCore.QRect(290, 260, 113, 32))
        self.Btn_StartScan_single_Efly.setObjectName("Btn_StartScan_single_Efly")
        ##self.Btn_StartScan_single_Efly.clicked.connect(self.E_fly)

        # Efly2 means stop scan
        self.Btn_StartScan_single_Efly_2 = QtWidgets.QPushButton(self.tab_XASfly)
        self.Btn_StartScan_single_Efly_2.setGeometry(QtCore.QRect(400, 260, 113, 32))
        self.Btn_StartScan_single_Efly_2.setObjectName("Btn_StartScan_single_Efly_2")

        # batch E scan
        self.label_Batchscan = QtWidgets.QLabel(self.tab_XASfly)
        self.label_Batchscan.setGeometry(QtCore.QRect(542, 265, 81, 16))
        self.label_Batchscan.setObjectName("label_Batchscan")
        self.Btn_StopScan_batch_Efly = QtWidgets.QPushButton(self.tab_XASfly)
        self.Btn_StopScan_batch_Efly.setGeometry(QtCore.QRect(900, 259, 113, 32))
        self.Btn_StopScan_batch_Efly.setObjectName("Btn_StopScan_batch_Efly")
        self.Btn_StartScan_Batch_Efly = QtWidgets.QPushButton(self.tab_XASfly)
        self.Btn_StartScan_Batch_Efly.setGeometry(QtCore.QRect(790, 259, 113, 32))
        self.Btn_StartScan_Batch_Efly.setObjectName("Btn_StartScan_Batch_Efly")
        self.lineEdit_BatchE_para = QtWidgets.QLineEdit(self.tab_XASfly)
        self.lineEdit_BatchE_para.setGeometry(QtCore.QRect(624, 264, 161, 21))
        self.lineEdit_BatchE_para.setObjectName("lineEdit_BatchE_para")
        self.label_BatchE_sample = QtWidgets.QLabel(self.tab_XASfly)
        self.label_BatchE_sample.setGeometry(QtCore.QRect(626, 246, 81, 16))
        self.label_BatchE_sample.setObjectName("label_BatchE_sample")
        self.tabWidget_main.addTab(self.tab_XASfly, "")

        # XASstep tab
        self.tab_XASstep = QtWidgets.QWidget()
        self.tab_XASstep.setObjectName("tab_XASstep")
        self.graphicsView_2 = PlotWidget(self.tab_XASstep)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 310, 1111, 491))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_XASstep_para = QtWidgets.QLabel(self.tab_XASstep)
        self.label_XASstep_para.setGeometry(QtCore.QRect(90, 40, 171, 16))
        self.label_XASstep_para.setObjectName("label_XASstep_para")
        self.tableWidget_XASstep_para = QtWidgets.QTableWidget(self.tab_XASstep)
        self.tableWidget_XASstep_para.setGeometry(QtCore.QRect(80, 60, 1071, 161))
        self.tableWidget_XASstep_para.setAlternatingRowColors(True)
        self.tableWidget_XASstep_para.setObjectName("tableWidget_XASstep_para")
        self.tableWidget_XASstep_para.setColumnCount(10)
        self.tableWidget_XASstep_para.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_XASstep_para.setHorizontalHeaderItem(9, item)
        self.label_XASstep_single = QtWidgets.QLabel(self.tab_XASstep)
        self.label_XASstep_single.setGeometry(QtCore.QRect(80, 260, 81, 16))
        self.label_XASstep_single.setObjectName("label_XASstep_single")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_XASstep)
        self.pushButton_13.setGeometry(QtCore.QRect(400, 257, 113, 32))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_XASstep)
        self.pushButton_14.setGeometry(QtCore.QRect(821, 255, 113, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox_XASstep_single = QtWidgets.QComboBox(self.tab_XASstep)
        self.comboBox_XASstep_single.setGeometry(QtCore.QRect(180, 260, 104, 26))
        self.comboBox_XASstep_single.setMouseTracking(False)
        self.comboBox_XASstep_single.setAcceptDrops(True)
        self.comboBox_XASstep_single.setObjectName("comboBox_XASstep_single")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.comboBox_XASstep_single.addItem("")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_XASstep)
        self.pushButton_15.setGeometry(QtCore.QRect(931, 255, 113, 32))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_19 = QtWidgets.QLabel(self.tab_XASstep)
        self.label_19.setGeometry(QtCore.QRect(570, 260, 81, 16))
        self.label_19.setObjectName("label_19")
        self.Btn_ = QtWidgets.QPushButton(self.tab_XASstep)
        self.Btn_.setGeometry(QtCore.QRect(290, 257, 113, 32))
        self.Btn_.setObjectName("Btn_")
        self.label_XASstep_sampleNo = QtWidgets.QLabel(self.tab_XASstep)
        self.label_XASstep_sampleNo.setGeometry(QtCore.QRect(180, 240, 81, 16))
        self.label_XASstep_sampleNo.setObjectName("label_XASstep_sampleNo")
        self.label_22 = QtWidgets.QLabel(self.tab_XASstep)
        self.label_22.setGeometry(QtCore.QRect(662, 242, 81, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_XASstep)
        self.lineEdit_2.setGeometry(QtCore.QRect(660, 260, 161, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget_main.addTab(self.tab_XASstep, "")

        # XRFmapping tab
        self.tab_XRF = QtWidgets.QWidget()
        self.tab_XRF.setObjectName("tab_XRF")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_XRF)
        self.tableWidget_4.setGeometry(QtCore.QRect(70, 50, 1011, 161))
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(11)
        self.tableWidget_4.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(10, item)
        self.label_23 = QtWidgets.QLabel(self.tab_XRF)
        self.label_23.setGeometry(QtCore.QRect(80, 20, 171, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_XRF)
        self.pushButton_18.setGeometry(QtCore.QRect(296, 248, 113, 32))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_XRF)
        self.pushButton_19.setGeometry(QtCore.QRect(926, 254, 113, 32))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_XRF)
        self.pushButton_20.setGeometry(QtCore.QRect(406, 248, 113, 32))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_24 = QtWidgets.QLabel(self.tab_XRF)
        self.label_24.setGeometry(QtCore.QRect(579, 259, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_XRF)
        self.label_25.setGeometry(QtCore.QRect(186, 231, 81, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_XRF)
        self.label_26.setGeometry(QtCore.QRect(86, 251, 81, 16))
        self.label_26.setObjectName("label_26")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_XRF)
        self.comboBox_4.setGeometry(QtCore.QRect(186, 251, 104, 26))
        self.comboBox_4.setMouseTracking(False)
        self.comboBox_4.setAcceptDrops(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_XRF)
        self.pushButton_21.setGeometry(QtCore.QRect(816, 254, 113, 32))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_XRF)
        self.pushButton_22.setGeometry(QtCore.QRect(850, 770, 113, 32))
        self.pushButton_22.setObjectName("pushButton_22")
        self.graphicsView_3 = PlotWidget(self.tab_XRF)
        self.graphicsView_3.setGeometry(QtCore.QRect(60, 320, 751, 491))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_XRF)
        self.lineEdit_3.setGeometry(QtCore.QRect(658, 258, 161, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_27 = QtWidgets.QLabel(self.tab_XRF)
        self.label_27.setGeometry(QtCore.QRect(660, 240, 81, 16))
        self.label_27.setObjectName("label_27")
        self.tabWidget_main.addTab(self.tab_XRF, "")
        self.tab_contact = QtWidgets.QWidget()
        self.tab_contact.setObjectName("tab_contact")
        self.tabWidget_main.addTab(self.tab_contact, "")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(130, 880, 921, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(30, 880, 60, 16))
        self.label_status.setObjectName("label_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(2)
        self.tabWidget_webcam.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Proposal.setText(_translate("MainWindow", "Proposal #"))
        self.label_SAF.setText(_translate("MainWindow", "SAF #"))
        self.label_username.setText(_translate("MainWindow", "User\'s name"))
        self.comboBox_edgeselect.setItemText(0, _translate("MainWindow", "Al K"))
        self.comboBox_edgeselect.setItemText(1, _translate("MainWindow", "Si K"))
        self.comboBox_edgeselect.setItemText(2, _translate("MainWindow", "P K"))
        self.comboBox_edgeselect.setItemText(3, _translate("MainWindow", "S K"))
        self.comboBox_edgeselect.setItemText(4, _translate("MainWindow", "Cl K"))
        self.comboBox_edgeselect.setItemText(5, _translate("MainWindow", "K K"))
        self.comboBox_edgeselect.setItemText(6, _translate("MainWindow", "Ca K"))
        self.label_edge.setText(_translate("MainWindow", "Edge"))
        self.label_edgeE.setText(_translate("MainWindow", "Edge energy"))
        self.Btn_moveE.setText(_translate("MainWindow", "Move E"))
        self.tabWidget_webcam.setTabText(self.tabWidget_webcam.indexOf(self.tab_cam01),
                                         _translate("MainWindow", "Cam01"))
        self.tabWidget_webcam.setTabText(self.tabWidget_webcam.indexOf(self.tab_cam02),
                                         _translate("MainWindow", "Cam02"))
        self.Btn_up.setText(_translate("MainWindow", "Up"))
        self.Btn_right.setText(_translate("MainWindow", "Right"))
        self.Btn_left.setText(_translate("MainWindow", "Left"))
        self.Btn_down.setText(_translate("MainWindow", "Down"))
        self.label_zpos.setText(_translate("MainWindow", "Z"))
        self.label_monoE.setText(_translate("MainWindow", "Energy"))
        self.label_currentE.setText(_translate("MainWindow", "Current energy"))
        self.Btn_save_current_position.setText(_translate("MainWindow", "Save current position"))
        self.Btn_shutter.setText(_translate("MainWindow", "Shutter open/close"))
        item = self.tableWidget_samplepos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_samplepos.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_samplepos.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_samplepos.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_samplepos.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_samplepos.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_samplepos.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_samplepos.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_samplepos.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_samplepos.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_samplepos.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_samplepos.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_samplepos.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_samplepos.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_samplepos.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_samplepos.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_samplepos.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_samplepos.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_samplepos.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_samplepos.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_samplepos.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_samplepos.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_samplepos.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_samplepos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_samplepos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget_samplepos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.tableWidget_samplepos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample name"))
        self.label_Xpress3.setText(_translate("MainWindow", "Xpress3"))
        self.label_ypos.setText(_translate("MainWindow", "Y"))
        self.label_xpos.setText(_translate("MainWindow", "X"))
        self.label_11.setText(_translate("MainWindow", "X position:"))
        self.Btn_zoomin.setText(_translate("MainWindow", "In"))
        self.label_12.setText(_translate("MainWindow", "Y position:"))
        self.label_13.setText(_translate("MainWindow", "Z position:"))
        self.label_CurrentE_display.setText(_translate("MainWindow", "Current E_display"))
        self.label_edgeE_display.setText(_translate("MainWindow", "Edge E_display"))
        self.Btn_zoomout.setText(_translate("MainWindow", "Out"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.label_XASfly_param.setText(_translate("MainWindow", "XAS Fly-scan parameters"))
        item = self.tableWidget_XASfly.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_XASfly.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_XASfly.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_XASfly.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_XASfly.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_XASfly.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_XASfly.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_XASfly.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_XASfly.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_XASfly.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_XASfly.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_XASfly.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_XASfly.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_XASfly.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_XASfly.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_XASfly.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_XASfly.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_XASfly.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_XASfly.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_XASfly.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_XASfly.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_XASfly.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_XASfly.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample name"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Start E"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "End E"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Scan rate"))
        item = self.tableWidget_XASfly.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "# scan"))
        self.label_Efly_scan.setText(_translate("MainWindow", "Single scan"))
        self.comboBox_Efly_single.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_Efly_single.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_Efly_single.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_Efly_single.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_Efly_single.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_Efly_single.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_Efly_single.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_Efly_single.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_Efly_single.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_Efly_single.setItemText(9, _translate("MainWindow", "10"))
        self.label_Efly_single_sample.setText(_translate("MainWindow", "Sample No."))
        self.Btn_StartScan_single_Efly.setText(_translate("MainWindow", "Start scan"))
        self.Btn_StartScan_single_Efly_2.setText(_translate("MainWindow", "Stop scan"))
        self.label_Batchscan.setText(_translate("MainWindow", "Batch scan"))
        self.Btn_StopScan_batch_Efly.setText(_translate("MainWindow", "Stop scan"))
        self.Btn_StartScan_Batch_Efly.setText(_translate("MainWindow", "Start scan"))
        self.label_BatchE_sample.setText(_translate("MainWindow", "Sample No."))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_XASfly),
                                       _translate("MainWindow", "XAS-Fly scan"))
        self.label_XASstep_para.setText(_translate("MainWindow", "XAS Step-scan parameters"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_XASstep_para.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample name"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Start E"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "E2"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "E3"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "End E"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Step size (E1,E2,E3,E4)"))
        item = self.tableWidget_XASstep_para.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "# scan"))
        self.label_XASstep_single.setText(_translate("MainWindow", "Single scan"))
        self.pushButton_13.setText(_translate("MainWindow", "Stop scan"))
        self.pushButton_14.setText(_translate("MainWindow", "Start scan"))
        self.comboBox_XASstep_single.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_XASstep_single.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_XASstep_single.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_XASstep_single.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_XASstep_single.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_XASstep_single.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_XASstep_single.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_XASstep_single.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_XASstep_single.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_XASstep_single.setItemText(9, _translate("MainWindow", "10"))
        self.pushButton_15.setText(_translate("MainWindow", "Stop scan"))
        self.label_19.setText(_translate("MainWindow", "Batch scan"))
        self.Btn_.setText(_translate("MainWindow", "Start scan"))
        self.label_XASstep_sampleNo.setText(_translate("MainWindow", "Sample No."))
        self.label_22.setText(_translate("MainWindow", "Sample No."))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_XASstep),
                                       _translate("MainWindow", "XAS-Step scan"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_4.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_4.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_4.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_4.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_4.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_4.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_4.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_4.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_4.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_4.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_4.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_4.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample name"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "X start"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "X stop"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "X step size"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "# scan"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Y stop"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Y step size"))
        item = self.tableWidget_4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "dwell time"))
        self.label_23.setText(_translate("MainWindow", "XRF mapping"))
        self.pushButton_18.setText(_translate("MainWindow", "Start scan"))
        self.pushButton_19.setText(_translate("MainWindow", "Stop scan"))
        self.pushButton_20.setText(_translate("MainWindow", "Stop scan"))
        self.label_24.setText(_translate("MainWindow", "Batch scan"))
        self.label_25.setText(_translate("MainWindow", "Sample No."))
        self.label_26.setText(_translate("MainWindow", "Single scan"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.pushButton_21.setText(_translate("MainWindow", "Start scan"))
        self.pushButton_22.setText(_translate("MainWindow", "Launch pyXRF"))
        self.label_27.setText(_translate("MainWindow", "Sample No."))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_XRF),
                                       _translate("MainWindow", "XRF imaging"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_contact),
                                       _translate("MainWindow", "Contact us"))
        self.label_status.setText(_translate("MainWindow", "Status"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())






